services:
  db:
    image: postgres:18
    container_name: library-db
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: library-backend
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    user: root

  front:
    build: ./front
    image: react-front
    command: sh -c "npm install && npm run start"
    ports:
      - "4000:4000"
    working_dir: /front
    volumes:
      - ./front:/front

volumes:
  db-data:
